Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,15 +13,23 @@ jobs:
           name: Check contexts env name
           background: true
           command: |
-            #while true; do
-              #sleep 5
-              #LATEST_COMMIT=$(git ls-remote $CIRCLE_REPOSITORY_URL | grep $CIRCLE_BRANCH | cut -f 1)
-              if [ "${CIRCLE_BRANCH}" != "${DISABLE_CIRCLECI}" ]; then
-                echo "Branch miss match"
-              #  curl -X POST "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_API_TOKEN"
-              fi
-              exit 99
+            ##while true; do
+            #  #sleep 5
+            #  #LATEST_COMMIT=$(git ls-remote $CIRCLE_REPOSITORY_URL | grep $CIRCLE_BRANCH | cut -f 1)
+            #  if [ "${CIRCLE_BRANCH}" != "${DISABLE_CIRCLECI}" ]; then
+            #    echo "Branch miss match"
+            #  #  curl -X POST "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_API_TOKEN"
+            #  fi
+            #  exit 99
             #done
+            if [[ ${CIRCLE_BRANCH}" == "${DISABLE_CIRCLECI}" ]]; then
+                   echo "CIRCLE_BRANCH match DISABLE_CIRCLECI"
+                   exit 0
+               else
+                   echo "CIRCLE_BRANCH miss match DISABLE_CIRCLECI"
+                   #echo "retry $i from 10"
+            fi
+            exit 99
 
   release:
     docker:
